# 这是一个基本工作流，可帮助您开始操作

name: 编译虚幻引擎

# 控制工作流何时运行
on:
  schedule:
    # 每10天定时启动
    - cron:  '0 0 10,20,30 * *'
  push:
    #特定分支(mian),
    branches:
      - main
    #特定tsgs
    #tags:
    #  - v
    #特定路径
    #paths:
    #  - 'Community-Applications-Moderators/*'
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:  
        - {
          name: "编译虚幻引擎",
          os: windows-latest
          }
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: MSVC Build CMD
        uses: ilammy/msvc-dev-cmd@v1
        with:
        arch: x64
      
- name: Download artifact
  # You may pin to the exact commit or the version.
  # uses: aochmann/actions-download-artifact@5709392f11b5937bd316e52687ad87f7deced5f5
  uses: aochmann/actions-download-artifact@1.0.4
  with:
    # GitHub token
    github_token: # optional, default is ${{github.token}}
    # Repository name with owner
    repo: EpicGames/UnrealEngine # optional, default is ${{github.repository}}
    # Artifact name (download all artifacts in not specified)
    name: # optional
    # Download latest artifact
    latest: true # optional
    # Artifact unpack location
    path: # optional, default is ./
